// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4290.TesterBot.subsystems;

import org.usfirst.frc4290.TesterBot.RobotMap;
import org.usfirst.frc4290.TesterBot.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Pneumatics extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid leftSolonoid = RobotMap.pneumaticsleftSolonoid;
    private final DoubleSolenoid climberSolonoid = RobotMap.pneumaticsClimberSolonoid;
    private final Relay spike = RobotMap.spike;
    private final Compressor compressor = RobotMap.pneumaticscompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	
    	setDefaultCommand(new RaiseLowerArm());
    }
    public void startCompressor(){
    	compressor.start();
    }
    
    public void raiseArm(){
    	leftSolonoid.set(Value.kForward);
    	
    }
    
    public void lowerArm(){
    	leftSolonoid.set(Value.kReverse);

    }
    
    public void stopArm(){
    	leftSolonoid.set(Value.kOff);

    }
    
    public void raiseClimber(){
    	climberSolonoid.set(Value.kForward);
    	
    }
    
    public void lowerClimber(){
    	climberSolonoid.set(Value.kReverse);

    }
    
    public void stopClimber(){
    	climberSolonoid.set(Value.kOff);

    }
    
}

